-- Blog Posts Table for OT2 Website
-- Run this in your Supabase SQL editor

CREATE TABLE IF NOT EXISTS blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  content TEXT NOT NULL,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  read_time TEXT DEFAULT '5 min read',
  category TEXT DEFAULT 'Productivity',
  slug TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for better performance
CREATE INDEX IF NOT EXISTS idx_blog_posts_date ON blog_posts(date DESC);
CREATE INDEX IF NOT EXISTS idx_blog_posts_category ON blog_posts(category);
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON blog_posts(slug);

-- Enable Row Level Security (RLS)
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

-- Create policy for read access (public)
CREATE POLICY "Public read access" ON blog_posts
  FOR SELECT USING (true);

-- Create policy for insert/update/delete (authenticated users only)
CREATE POLICY "Authenticated write access" ON blog_posts
  FOR ALL USING (
    auth.role() = 'authenticated'
  );

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger to automatically update updated_at
CREATE TRIGGER update_blog_posts_updated_at
  BEFORE UPDATE ON blog_posts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Insert sample data (optional)
INSERT INTO blog_posts (title, excerpt, content, date, read_time, category, slug) VALUES
(
  'Act on What Matters, NOW!',
  'Todo lists capture "what you want to do". OT² helps you act on what you actually need to do—right now.',
  '<h2>Todo lists capture "what you want to do". OT² goes further.</h2>
  <p>We''ve all been there. You open your todo list app, feel the initial rush of accomplishment as you brain-dump tasks, and then... nothing happens.</p>
  <p>The list sits there, growing longer with every passing day. More tasks pile up. More guilt accumulates. More overwhelm sets in.</p>',
  '2026-04-20',
  '6 min read',
  'Productivity',
  'act-on-what-matters'
),
(
  'Systems Beat Goals',
  '"You do not rise to the level of your goals. You fall to the level of your systems." — James Clear',
  '<h2>"You do not rise to the level of your goals. You fall to the level of your systems." — James Clear</h2>
  <p>This quote changed everything for me. And it should change how you think about your productivity forever.</p>
  <p>Because here''s the brutal truth: <strong>without a system, goals are just wishes</strong>.</p>',
  '2026-04-18',
  '7 min read',
  'Systems',
  'systems-beat-goals'
),
(
  'Your Personal Coach, Always With You',
  'Stop wasting thousands on coaching programs. Get Socrates as your personal 1-1 coach, always accessible.',
  '<h2>You need a coach. But you don''t need to pay thousands and then fall back to old ways.</h2>
  <p>The concept is familiar and proven. You identify a gap in your performance. You sign up for a coaching program—life coaching, career coaching, productivity coaching.</p>',
  '2026-04-16',
  '7 min read',
  'Coaching',
  'personal-coach-always'
);
